export const ALL_SERVICES_REQUEST = "ALL_SERVICES_REQUEST";
export const ALL_SERVICES_SUCCESS = "ALL_SERVICES_SUCCESS";
export const ALL_SERVICES_FAIL = "ALL_SERVICES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SERVICE_DETAILS_REQUEST = "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCCESS = "SERVICE_DETAILS_SUCCESS";
export const SERVICE_DETAILS_FAIL = "SERVICE_DETAILS_FAIL";

export const NEW_REVIEWS_REQUESTS = "NEW_REVIEWS_REQUESTS";
export const NEW_REVIEWS_SUCCESSS = "NEW_REVIEWS_SUCCESSS";
export const NEW_REVIEWS_RESETSS = "NEW_REVIEWS_RESETSS";
export const NEW_REVIEWS_FAILS = "NEW_REVIEWS_FAILS";

export const ADMIN_SERVICES_REQUEST = "ADMIN_SERVICES_REQUEST";
export const ADMIN_SERVICES_SUCCESS = "ADMIN_SERVICES_SUCCESS";
export const ADMIN_SERVICES_FAIL = "ADMIN_SERVICES_FAIL";

export const NEW_SERVICE_REQUEST = "NEW_SERVICE_REQUEST";
export const NEW_SERVICE_SUCCESS = "NEW_SERVICE_SUCCESS";
export const NEW_SERVICE_RESET = "NEW_SERVICE_RESET";
export const NEW_SERVICE_FAIL = "NEW_SERVICE_FAIL";

export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_RESET = "DELETE_SERVICE_RESET";
export const DELETE_SERVICE_FAIL = "DELETE_SERVICE_FAIL";

export const UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_RESET = "UPDATE_SERVICE_RESET";
export const UPDATE_SERVICE_FAIL = "UPDATE_SERVICE_FAIL";

export const GET_REVIEWS_REQUESTS = "GET_REVIEWS_REQUESTS";
export const GET_REVIEWS_SUCCESSS = "GET_REVIEWS_SUCCESSS";
export const GET_REVIEWS_FAILS = "GET_REVIEWS_FAILS";

export const DELETE_REVIEWS_REQUESTS = "DELETE_REVIEWS_REQUESTS";
export const DELETE_REVIEWS_SUCCESSS = "DELETE_REVIEWS_SUCCESSS";
export const DELETE_REVIEWS_RESETS = "DELETE_REVIEWS_RESETS";
export const DELETE_REVIEWS_FAILS = "DELETE_REVIEWS_FAILS";